:sectnums!:
:ditto: &#12291;

[appendix]
[[fblangref-appx-profiler]]
= Таблицы плагинов

Таблицы плагинов — это таблицы или представления, созданные для или с помощью различных плагинов для движка Firebird. Стандартные таблицы плагинов имеют префикс `PLG$` (но могут иметь и другие).

Таблицы плагинов не всегда существуют. Например, некоторые таблицы существуют только в базе данных безопасности, а другие таблицы будут созданы только при первом использовании плагина.

В этом приложении описаны только таблицы плагинов, созданные плагинами, включенными в стандартную поставку Firebird 5.0.

Таблицы плагинов не считаются системными таблицами.

== Плагин профилирования `Default_Profiler`

Таблицы профилировщика, перечисленные в этом приложении (начиная с PLG$PROF_), создаются плагином Default_Profiler. Если создан собственный плагин профилировщика, он может использовать другие имена таблиц.

Таблицы моментальных снимков, а также представления и последовательности, автоматически создаются при первом использовании профилировщика. Они принадлежат текущему пользователю с разрешениями на чтение/запись для `PUBLIC`.

Когда сеанс удаляется, связанные данные в других таблицах моментальных снимков профилировщика также автоматически удаляются с помощью внешних ключей с опцией `DELETE CASCADE`.

Ниже приведен список таблиц, в которых хранятся данные профиля.

=== Таблица `PLG$PROF_SESSIONS`

Таблица `PLG$PROF_SESSIONS` содержит информацию о сессиях профилирования.

- `PROFILE_ID` type `BIGINT` - идентификатор сессии профилирования
- `ATTACHMENT_ID` type `BIGINT` - идентификатор соединения для которого производится профилирование
- `USER_NAME` type `CHAR(63) CHARACTER SET UTF8` - имя пользователя
- `DESCRIPTION` type `VARCHAR(255) CHARACTER SET UTF8` - описание переданное в параметре `RDB$PROFILER.START_SESSION`
- `START_TIMESTAMP` type `TIMESTAMP WITH TIME ZONE` - момент начала сессии профилирования
- `FINISH_TIMESTAMP` type `TIMESTAMP WITH TIME ZONE` - момент окончания сессии профилирования (NULL если сессия не завершена)
- Первичный ключ: `PROFILE_ID`

=== Таблица `PLG$PROF_STATEMENTS`

Таблица `PLG$PROF_STATEMENTS` содержит информацию об SQL операторах.

- `PROFILE_ID` type `BIGINT` - идентификатор сессии профилирования
- `STATEMENT_ID` type `BIGINT` - идентификатор оператора
- `PARENT_STATEMENT_ID` type `BIGINT` - родительский идентификатор запроса - относится к подпрограммам.
- `STATEMENT_TYPE` type `VARCHAR(20) CHARACTER SET UTF8` - типа оператора BLOCK, FUNCTION, PROCEDURE или TRIGGER
- `PACKAGE_NAME` type `CHAR(63) CHARACTER SET UTF8` - Имя пакета
- `ROUTINE_NAME` type `CHAR(63) CHARACTER SET UTF8` - Имя функции, процедуры или триггера
- `SQL_TEXT` type `BLOB subtype TEXT CHARACTER SET UTF8` - SQL текст для типа BLOCK
- Первичный ключ: `PROFILE_ID, STATEMENT_ID`

=== Таблица `PLG$PROF_RECORD_SOURCES`

Таблица `PLG$PROF_RECORD_SOURCES` содержит информацию об источниках записей.

- `PROFILE_ID` type `BIGINT` - идентификатор сессии профилирования
- `STATEMENT_ID` type `BIGINT` - идентификатор оператора
- `CURSOR_ID` type `BIGINT` - идентификатор курсора
- `RECORD_SOURCE_ID` type `BIGINT` - идентификатор источника записи
- `PARENT_RECORD_SOURCE_ID` type `BIGINT` - идентификатор источника родительской записи
- `ACCESS_PATH` type `VARCHAR(255) CHARACTER SET UTF8` - путь доступа к источнику записи
- Первичный ключ: `PROFILE_ID, STATEMENT_ID, CURSOR_ID, RECORD_SOURCE_ID`

=== Таблица `PLG$PROF_REQUESTS`

- `PROFILE_ID` type `BIGINT` - идентификатор сессии профилирования
- `REQUEST_ID` type `BIGINT` - идентификатор запроса
- `STATEMENT_ID` type `BIGINT` - идентификатор оператора
- `CALLER_REQUEST_ID` type `BIGINT` - идентификатор вызывающего запроса
- `START_TIMESTAMP` type `TIMESTAMP WITH TIME ZONE` - момент, когда данный запрос впервые собрал данные профилирования
- `FINISH_TIMESTAMP` type `TIMESTAMP WITH TIME ZONE` - момент завершения запроса
- `TOTAL_ELAPSED_TIME` type `BIGINT` - Накопленное время выполнения запроса (в наносекундах)
- Первичный ключ: `PROFILE_ID, REQUEST_ID`

=== Таблица `PLG$PROF_PSQL_STATS`

Таблица `PLG$PROF_STATEMENTS` содержит PSQL статистику.

- `PROFILE_ID` type `BIGINT` - идентификатор сессии профилирования
- `REQUEST_ID` type `BIGINT` - идентификатор запроса
- `LINE_NUM` type `INTEGER` - номер строки оператора
- `COLUMN_NUM` type `INTEGER` - номер столбца оператора
- `STATEMENT_ID` type `BIGINT` - идентификатор оператора
- `COUNTER` type `BIGINT` - количество выполнений для номера строки/столбца
- `MIN_ELAPSED_TIME` type `BIGINT` - Минимальное время выполнения (в наносекундах) для строки/столбца
- `MAX_ELAPSED_TIME` type `BIGINT` - Максимальное время выполнения (в наносекундах) для строки/столбца
- `TOTAL_ELAPSED_TIME` type `BIGINT` - Накопленное время выполнения (в наносекундах) для строки/столбца
- Первичный ключ: `PROFILE_ID, REQUEST_ID, LINE_NUM, COLUMN_NUM`

=== Таблица `PLG$PROF_RECORD_SOURCE_STATS`

Таблица `PLG$PROF_RECORD_SOURCES` содержит статистику источников записей.

- `PROFILE_ID` type `BIGINT` - идентификатор сессии профилирования
- `REQUEST_ID` type `BIGINT` - идентификатор запроса
- `CURSOR_ID` type `BIGINT` - идентификатор курсора
- `RECORD_SOURCE_ID` type `BIGINT` - идентификатор источника записи
- `STATEMENT_ID` type `BIGINT` - идентификатор оператора
- `OPEN_COUNTER` type `BIGINT` - количество открытий источника записи
- `OPEN_MIN_ELAPSED_TIME` type `BIGINT` - Минимальное время открытия источника записи (в наносекундах)
- `OPEN_MAX_ELAPSED_TIME` type `BIGINT` - Максимальное время открытия источника записи (в наносекундах)
- `OPEN_TOTAL_ELAPSED_TIME` type `BIGINT` - Накопленное время открытия источника записи (в наносекундах)
- `FETCH_COUNTER` type `BIGINT` - Количество извлечений из источника записи
- `FETCH_MIN_ELAPSED_TIME` type `BIGINT` - Минимальное время извлечения записи из источника записи (в наносекундах)
- `FETCH_MAX_ELAPSED_TIME` type `BIGINT` - Максимальное время извлечения записи из источника записи (в наносекундах)
- `FETCH_TOTAL_ELAPSED_TIME` type `BIGINT` - Накопленное время извлечения записей из источника записи (в наносекундах)
- Первичный ключ: `PROFILE_ID, REQUEST_ID, CURSOR_ID, RECORD_SOURCE_ID`

=== Представление `PLG$PROF_STATEMENT_STATS_VIEW`

[source,sql]
----
select req.profile_id,
       req.statement_id,
       sta.statement_type,
       sta.package_name,
       sta.routine_name,
       sta.parent_statement_id,
       sta_parent.statement_type parent_statement_type,
       sta_parent.routine_name parent_routine_name,
       (select sql_text
          from plg$prof_statements
          where profile_id = req.profile_id and
                statement_id = coalesce(sta.parent_statement_id, req.statement_id)
       ) sql_text,
       count(*) counter,
       min(req.total_elapsed_time) min_elapsed_time,
       max(req.total_elapsed_time) max_elapsed_time,
       cast(sum(req.total_elapsed_time) as bigint) total_elapsed_time,
       cast(sum(req.total_elapsed_time) / count(*) as bigint) avg_elapsed_time
  from plg$prof_requests req
  join plg$prof_statements sta
    on sta.profile_id = req.profile_id and
       sta.statement_id = req.statement_id
  left join plg$prof_statements sta_parent
    on sta_parent.profile_id = sta.profile_id and
       sta_parent.statement_id = sta.parent_statement_id
  group by req.profile_id,
           req.statement_id,
           sta.statement_type,
           sta.package_name,
           sta.routine_name,
           sta.parent_statement_id,
           sta_parent.statement_type,
           sta_parent.routine_name
  order by sum(req.total_elapsed_time) desc
----

=== Представление `PLG$PROF_PSQL_STATS_VIEW`

[source,sql]
----
select pstat.profile_id,
       pstat.statement_id,
       sta.statement_type,
       sta.package_name,
       sta.routine_name,
       sta.parent_statement_id,
       sta_parent.statement_type parent_statement_type,
       sta_parent.routine_name parent_routine_name,
       (select sql_text
          from plg$prof_statements
          where profile_id = pstat.profile_id and
                statement_id = coalesce(sta.parent_statement_id, pstat.statement_id)
       ) sql_text,
       pstat.line_num,
       pstat.column_num,
       cast(sum(pstat.counter) as bigint) counter,
       min(pstat.min_elapsed_time) min_elapsed_time,
       max(pstat.max_elapsed_time) max_elapsed_time,
       cast(sum(pstat.total_elapsed_time) as bigint) total_elapsed_time,
       cast(sum(pstat.total_elapsed_time) / nullif(sum(pstat.counter), 0) as bigint) avg_elapsed_time
  from plg$prof_psql_stats pstat
  join plg$prof_statements sta
    on sta.profile_id = pstat.profile_id and
       sta.statement_id = pstat.statement_id
  left join plg$prof_statements sta_parent
    on sta_parent.profile_id = sta.profile_id and
       sta_parent.statement_id = sta.parent_statement_id
  group by pstat.profile_id,
           pstat.statement_id,
           sta.statement_type,
           sta.package_name,
           sta.routine_name,
           sta.parent_statement_id,
           sta_parent.statement_type,
           sta_parent.routine_name,
           pstat.line_num,
           pstat.column_num
  order by sum(pstat.total_elapsed_time) desc
----

=== Представление `PLG$PROF_RECORD_SOURCE_STATS_VIEW`

[source,sql]
----
select rstat.profile_id,
       rstat.statement_id,
       sta.statement_type,
       sta.package_name,
       sta.routine_name,
       sta.parent_statement_id,
       sta_parent.statement_type parent_statement_type,
       sta_parent.routine_name parent_routine_name,
       (select sql_text
          from plg$prof_statements
          where profile_id = rstat.profile_id and
                statement_id = coalesce(sta.parent_statement_id, rstat.statement_id)
       ) sql_text,
       rstat.cursor_id,
       rstat.record_source_id,
       recsrc.parent_record_source_id,
       recsrc.access_path,
       cast(sum(rstat.open_counter) as bigint) open_counter,
       min(rstat.open_min_elapsed_time) open_min_elapsed_time,
       max(rstat.open_max_elapsed_time) open_max_elapsed_time,
       cast(sum(rstat.open_total_elapsed_time) as bigint) open_total_elapsed_time,
       cast(sum(rstat.open_total_elapsed_time) / nullif(sum(rstat.open_counter), 0) as bigint) open_avg_elapsed_time,
       cast(sum(rstat.fetch_counter) as bigint) fetch_counter,
       min(rstat.fetch_min_elapsed_time) fetch_min_elapsed_time,
       max(rstat.fetch_max_elapsed_time) fetch_max_elapsed_time,
       cast(sum(rstat.fetch_total_elapsed_time) as bigint) fetch_total_elapsed_time,
       cast(sum(rstat.fetch_total_elapsed_time) / nullif(sum(rstat.fetch_counter), 0) as bigint) fetch_avg_elapsed_time,
       cast(coalesce(sum(rstat.open_total_elapsed_time), 0) + coalesce(sum(rstat.fetch_total_elapsed_time), 0) as bigint) open_fetch_total_elapsed_time
  from plg$prof_record_source_stats rstat
  join plg$prof_record_sources recsrc
    on recsrc.profile_id = rstat.profile_id and
       recsrc.statement_id = rstat.statement_id and
       recsrc.cursor_id = rstat.cursor_id and
       recsrc.record_source_id = rstat.record_source_id
  join plg$prof_statements sta
    on sta.profile_id = rstat.profile_id and
       sta.statement_id = rstat.statement_id
  left join plg$prof_statements sta_parent
    on sta_parent.profile_id = sta.profile_id and
       sta_parent.statement_id = sta.parent_statement_id
  group by rstat.profile_id,
           rstat.statement_id,
           sta.statement_type,
           sta.package_name,
           sta.routine_name,
           sta.parent_statement_id,
           sta_parent.statement_type,
           sta_parent.routine_name,
           rstat.cursor_id,
           rstat.record_source_id,
           recsrc.parent_record_source_id,
           recsrc.access_path
  order by coalesce(sum(rstat.open_total_elapsed_time), 0) + coalesce(sum(rstat.fetch_total_elapsed_time), 0) desc
----
