:sectnums!:
:ditto: &#12291;

[appendix]
[[fblangref-appx-plgtables]]
= Таблицы плагинов

Таблицы плагинов — это таблицы или представления, созданные для или с помощью различных плагинов для движка Firebird. Стандартные таблицы плагинов имеют префикс `PLG$` (но могут иметь и другие).

Таблицы плагинов не всегда существуют. Например, некоторые таблицы существуют только в базе данных безопасности, а другие таблицы будут созданы только при первом использовании плагина.

В этом приложении описаны только таблицы плагинов, созданные плагинами, включенными в стандартную поставку Firebird 5.0.

Таблицы плагинов не считаются системными таблицами.

== Плагин профилирования `Default_Profiler`

Таблицы профилировщика, перечисленные в этом приложении (имеющие префикс PLG$PROF_), создаются плагином Default_Profiler. Если создан собственный плагин профилировщика, он может использовать другие имена таблиц.

Таблицы моментальных снимков, а также представления и последовательности, автоматически создаются при первом использовании профилировщика. Они принадлежат текущему пользователю с разрешениями на чтение/запись для `PUBLIC`.

Когда сеанс удаляется, связанные данные в других таблицах моментальных снимков профилировщика также автоматически удаляются с помощью внешних ключей с опцией `DELETE CASCADE`.

Ниже приведен список таблиц, в которых хранятся данные профиля.

`PLG$PROF_SESSIONS`:: информация о сессиях профилирования.
`PLG$PROF_STATEMENTS`:: информация об SQL операторах.
`PLG$PROF_CURSORS`:: информация о курсорах.
`PLG$PROF_RECORD_SOURCES`:: информация об источниках записей.
`PLG$PROF_REQUESTS`:: информация об SQL запросах.
`PLG$PROF_PSQL_STATS`:: PSQL статистика.
`PLG$PROF_RECORD_SOURCE_STATS`:: статистика источников записей.

Кроме того, плагин `Default_Profiler` создаёт несколько представлений. Эти представления помогают извлекать данные профилирования, агрегированные на уровне операторов.

Они должны быть предпочтительным способом анализа собранных данных. Их также можно использовать вместе с таблицами для получения дополнительных данных, отсутствующих в представлениях.

После того, как «горячие точки» найдены, можно детализировать данные на уровне запроса через таблицы.

Ниже приведен список представлений, созданных профилировщиком:

`PLG$PROF_STATEMENT_STATS_VIEW`:: агрегированная статистика SQL операторов.
`PLG$PROF_PSQL_STATS_VIEW`:: агрегированная PSQL статистика.
`PLG$PROF_RECORD_SOURCE_STATS_VIEW`:: агрегированная статистика по источникам записей.


=== Таблица `PLG$PROF_SESSIONS`

Таблица `PLG$PROF_SESSIONS` содержит информацию о сессиях профилирования.

.Описание столбцов таблицы `PLG$PROF_SESSIONS`
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Наименование столбца
^| Тип данных
^| Описание

|PROFILE_ID
|BIGINT
|идентификатор сессии профилирования

|ATTACHMENT_ID
|BIGINT
|идентификатор соединения для которого производится профилирование

|USER_NAME
|CHAR(63)
|имя пользователя

|DESCRIPTION
|VARCHAR(255)
|описание переданное в параметре `RDB$PROFILER.START_SESSION`

|START_TIMESTAMP
|TIMESTAMP WITH TIME ZONE
|момент начала сессии профилирования

|FINISH_TIMESTAMP
|TIMESTAMP WITH TIME ZONE
|момент окончания сессии профилирования (NULL если сессия не завершена)
|===

Первичный ключ: `PROFILE_ID`

=== Таблица `PLG$PROF_STATEMENTS`

Таблица `PLG$PROF_STATEMENTS` содержит информацию об SQL операторах.

.Описание столбцов таблицы `PLG$PROF_STATEMENTS`
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Наименование столбца
^| Тип данных
^| Описание

|PROFILE_ID
|BIGINT
|идентификатор сессии профилирования

|STATEMENT_ID
|BIGINT
|идентификатор оператора

|PARENT_STATEMENT_ID
|BIGINT
|родительский идентификатор запроса - относится к подпрограммам.

|STATEMENT_TYPE
|VARCHAR(20)
|типа оператора BLOCK, FUNCTION, PROCEDURE или TRIGGER

|PACKAGE_NAME
|CHAR(63)
|Имя пакета

|ROUTINE_NAME
|CHAR(63)
|Имя функции, процедуры или триггера

|SQL_TEXT
|BLOB SUB_TYPE TEXT
|SQL текст для типа BLOCK
|===

Первичный ключ: `PROFILE_ID, STATEMENT_ID`

## Table `PLG$PROF_CURSORS`

Таблица `PLG$PROF_CURSORS` содержит информацию о курсорах.

.Описание столбцов таблицы `PLG$PROF_CURSORS`
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Наименование столбца
^| Тип данных
^| Описание

|PROFILE_ID
|BIGINT
|идентификатор сессии профилирования

|STATEMENT_ID
|BIGINT
|идентификатор оператора

|CURSOR_ID
|BIGINT
|идентификатор курсора

|NAME
|CHAR(63)
|имя явно объявленного курсора

|LINE_NUM
|INTEGER
|номер строки в которой определён курсор

|COLUMN_NUM
|INTEGER
|номер столбца в котором определён курсор
|===

 Первичный ключ `PROFILE_ID, STATEMENT_ID, CURSOR_ID`

=== Таблица `PLG$PROF_RECORD_SOURCES`

Таблица `PLG$PROF_RECORD_SOURCES` содержит информацию об источниках записей.

.Описание столбцов таблицы `PLG$PROF_RECORD_SOURCES`
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Наименование столбца
^| Тип данных
^| Описание

|PROFILE_ID
|BIGINT
|идентификатор сессии профилирования

|STATEMENT_ID
|BIGINT
|идентификатор оператора

|CURSOR_ID
|BIGINT
|идентификатор курсора

|RECORD_SOURCE_ID
|BIGINT
|идентификатор источника записи

|PARENT_RECORD_SOURCE_ID
|BIGINT
|идентификатор источника родительской записи

|LEVEL
|INTEGER
|уровень метода доступа. Необходим для расчёта отступов при конструировании плана.

|ACCESS_PATH
|VARCHAR(255)
|путь доступа к источнику записи
|===

Первичный ключ: `PROFILE_ID, STATEMENT_ID, CURSOR_ID, RECORD_SOURCE_ID`

=== Таблица `PLG$PROF_REQUESTS`

Таблица `PLG$PROF_REQUESTS` содержит информацию об SQL запросах.

.Описание столбцов таблицы `PLG$PROF_REQUESTS`
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Наименование столбца
^| Тип данных
^| Описание

|PROFILE_ID
|BIGINT
|идентификатор сессии профилирования

|REQUEST_ID
|BIGINT
|идентификатор запроса

|STATEMENT_ID
|BIGINT
|идентификатор оператора

|CALLER_REQUEST_ID
|BIGINT
|идентификатор вызывающего запроса

|START_TIMESTAMP
|TIMESTAMP WITH TIME ZONE
|момент, когда данный запрос впервые собрал данные профилирования

|FINISH_TIMESTAMP
|TIMESTAMP WITH TIME ZONE
|момент завершения запроса

|TOTAL_ELAPSED_TIME
|BIGINT
|Накопленное время выполнения запроса (в наносекундах)
|===

Первичный ключ: `PROFILE_ID, REQUEST_ID`.

=== Таблица `PLG$PROF_PSQL_STATS`

Таблица `PLG$PROF_PSQL_STATS` содержит PSQL статистику.

.Описание столбцов таблицы `PLG$PROF_PSQL_STATS`
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Наименование столбца
^| Тип данных
^| Описание

|PROFILE_ID
|BIGINT
|идентификатор сессии профилирования

|REQUEST_ID
|BIGINT
|идентификатор запроса

|LINE_NUM
|INTEGER
|номер строки оператора

|COLUMN_NUM
|INTEGER
|номер столбца оператора

|STATEMENT_ID
|BIGINT
|идентификатор оператора

|COUNTER
|BIGINT
|количество выполнений для номера строки/столбца

|MIN_ELAPSED_TIME
|BIGINT
|Минимальное время выполнения (в наносекундах) для строки/столбца

|MAX_ELAPSED_TIME
|BIGINT
|Максимальное время выполнения (в наносекундах) для строки/столбца

|TOTAL_ELAPSED_TIME
|BIGINT
|Накопленное время выполнения (в наносекундах) для строки/столбца
|===

Первичный ключ: `PROFILE_ID, REQUEST_ID, LINE_NUM, COLUMN_NUM`.

=== Таблица `PLG$PROF_RECORD_SOURCE_STATS`

Таблица `PLG$PROF_RECORD_SOURCES` содержит статистику источников записей.

.Описание столбцов таблицы `PLG$PROF_RECORD_SOURCE_STATS`
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Наименование столбца
^| Тип данных
^| Описание

|PROFILE_ID
|BIGINT
|идентификатор сессии профилирования

|REQUEST_ID
|BIGINT
|идентификатор запроса

|CURSOR_ID
|BIGINT
|идентификатор курсора

|RECORD_SOURCE_ID
|BIGINT
|идентификатор источника записи

|STATEMENT_ID
|BIGINT
|идентификатор оператора

|OPEN_COUNTER
|BIGINT
|количество открытий источника записи

|OPEN_MIN_ELAPSED_TIME
|BIGINT
|Минимальное время открытия источника записи (в наносекундах)

|OPEN_MAX_ELAPSED_TIME
|BIGINT
|Максимальное время открытия источника записи (в наносекундах)

|OPEN_TOTAL_ELAPSED_TIME
|BIGINT
|Накопленное время открытия источника записи (в наносекундах)

|FETCH_COUNTER
|BIGINT
|Количество извлечений из источника записи

|FETCH_MIN_ELAPSED_TIME
|BIGINT
|Минимальное время извлечения записи из источника записи (в наносекундах)

|FETCH_MAX_ELAPSED_TIME
|BIGINT
|Максимальное время извлечения записи из источника записи (в наносекундах)

|FETCH_TOTAL_ELAPSED_TIME
|BIGINT
|Накопленное время извлечения записей из источника записи (в наносекундах)
|===

Первичный ключ: `PROFILE_ID, REQUEST_ID, CURSOR_ID, RECORD_SOURCE_ID`

=== Представление `PLG$PROF_STATEMENT_STATS_VIEW`

Представление `PLG$PROF_STATEMENT_STATS_VIEW` содержит агрегированную статистику SQL операторов.

.Описание столбцов представления `PLG$PROF_STATEMENT_STATS_VIEW`
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Наименование столбца
^| Тип данных
^| Описание

|PROFILE_ID
|BIGINT
|идентификатор сессии профилирования

|STATEMENT_ID
|BIGINT
|идентификатор оператора

|STATEMENT_TYPE
|VARCHAR(20)
|типа оператора BLOCK, FUNCTION, PROCEDURE или TRIGGER

|PACKAGE_NAME
|CHAR(63)
|Имя пакета

|ROUTINE_NAME
|CHAR(63)
|Имя функции, процедуры или триггера

|PARENT_STATEMENT_ID
|BIGINT
|идентификатор родительского оператора

|PARENT_STATEMENT_TYPE
|VARCHAR(20)
|типа родительского оператора BLOCK, FUNCTION, PROCEDURE или TRIGGER

|PARENT_ROUTINE_NAME
|CHAR(63)
|Имя родительской функции, процедуры или триггера

|SQL_TEXT
|BLOB SUB_TYPE TEXT
|SQL текст для типа BLOCK

|COUNTER
|BIGINT
|количество выполнений для номера строки/столбца

|MIN_ELAPSED_TIME
|BIGINT
|Минимальное время выполнения (в наносекундах) для строки/столбца

|MAX_ELAPSED_TIME
|BIGINT
|Максимальное время выполнения (в наносекундах) для строки/столбца

|TOTAL_ELAPSED_TIME
|BIGINT
|Накопленное время выполнения (в наносекундах) для строки/столбца

|AVG_ELAPSED_TIME
|BIGINT
|Среднее время выполнения (в наносекундах) для строки/столбца
|===

[source,sql]
----
select req.profile_id,
       req.statement_id,
       sta.statement_type,
       sta.package_name,
       sta.routine_name,
       sta.parent_statement_id,
       sta_parent.statement_type parent_statement_type,
       sta_parent.routine_name parent_routine_name,
       (select sql_text
          from plg$prof_statements
          where profile_id = req.profile_id and
                statement_id = coalesce(sta.parent_statement_id, req.statement_id)
       ) sql_text,
       count(*) counter,
       min(req.total_elapsed_time) min_elapsed_time,
       max(req.total_elapsed_time) max_elapsed_time,
       cast(sum(req.total_elapsed_time) as bigint) total_elapsed_time,
       cast(sum(req.total_elapsed_time) / count(*) as bigint) avg_elapsed_time
  from plg$prof_requests req
  join plg$prof_statements sta
    on sta.profile_id = req.profile_id and
       sta.statement_id = req.statement_id
  left join plg$prof_statements sta_parent
    on sta_parent.profile_id = sta.profile_id and
       sta_parent.statement_id = sta.parent_statement_id
  group by req.profile_id,
           req.statement_id,
           sta.statement_type,
           sta.package_name,
           sta.routine_name,
           sta.parent_statement_id,
           sta_parent.statement_type,
           sta_parent.routine_name
  order by sum(req.total_elapsed_time) desc
----

=== Представление `PLG$PROF_PSQL_STATS_VIEW`

Представление `PLG$PROF_PSQL_STATS_VIEW` содержит агрегированную PSQL статистику.

.Описание столбцов представления `PLG$PROF_PSQL_STATS_VIEW`
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Наименование столбца
^| Тип данных
^| Описание

|PROFILE_ID
|BIGINT
|идентификатор сессии профилирования

|STATEMENT_ID
|BIGINT
|идентификатор оператора

|STATEMENT_TYPE
|VARCHAR(20)
|типа оператора BLOCK, FUNCTION, PROCEDURE или TRIGGER

|PACKAGE_NAME
|CHAR(63)
|Имя пакета

|ROUTINE_NAME
|CHAR(63)
|Имя функции, процедуры или триггера

|PARENT_STATEMENT_ID
|BIGINT
|идентификатор родительского оператора

|PARENT_STATEMENT_TYPE
|VARCHAR(20)
|типа родительского оператора BLOCK, FUNCTION, PROCEDURE или TRIGGER

|PARENT_ROUTINE_NAME
|CHAR(63)
|Имя родительской функции, процедуры или триггера

|SQL_TEXT
|BLOB SUB_TYPE TEXT
|SQL текст для типа BLOCK

|LINE_NUM
|INTEGER
|номер строки оператора

|COLUMN_NUM
|INTEGER
|номер столбца оператора

|COUNTER
|BIGINT
|количество выполнений для номера строки/столбца

|MIN_ELAPSED_TIME
|BIGINT
|Минимальное время выполнения (в наносекундах) для строки/столбца

|MAX_ELAPSED_TIME
|BIGINT
|Максимальное время выполнения (в наносекундах) для строки/столбца

|TOTAL_ELAPSED_TIME
|BIGINT
|Накопленное время выполнения (в наносекундах) для строки/столбца

|AVG_ELAPSED_TIME
|BIGINT
|Среднее время выполнения (в наносекундах) для строки/столбца
|===

[source,sql]
----
select pstat.profile_id,
       pstat.statement_id,
       sta.statement_type,
       sta.package_name,
       sta.routine_name,
       sta.parent_statement_id,
       sta_parent.statement_type parent_statement_type,
       sta_parent.routine_name parent_routine_name,
       (select sql_text
          from plg$prof_statements
          where profile_id = pstat.profile_id and
                statement_id = coalesce(sta.parent_statement_id, pstat.statement_id)
       ) sql_text,
       pstat.line_num,
       pstat.column_num,
       cast(sum(pstat.counter) as bigint) counter,
       min(pstat.min_elapsed_time) min_elapsed_time,
       max(pstat.max_elapsed_time) max_elapsed_time,
       cast(sum(pstat.total_elapsed_time) as bigint) total_elapsed_time,
       cast(sum(pstat.total_elapsed_time) / nullif(sum(pstat.counter), 0) as bigint) avg_elapsed_time
  from plg$prof_psql_stats pstat
  join plg$prof_statements sta
    on sta.profile_id = pstat.profile_id and
       sta.statement_id = pstat.statement_id
  left join plg$prof_statements sta_parent
    on sta_parent.profile_id = sta.profile_id and
       sta_parent.statement_id = sta.parent_statement_id
  group by pstat.profile_id,
           pstat.statement_id,
           sta.statement_type,
           sta.package_name,
           sta.routine_name,
           sta.parent_statement_id,
           sta_parent.statement_type,
           sta_parent.routine_name,
           pstat.line_num,
           pstat.column_num
  order by sum(pstat.total_elapsed_time) desc
----

=== Представление `PLG$PROF_RECORD_SOURCE_STATS_VIEW`

Представление `PLG$PROF_RECORD_SOURCE_STATS_VIEW` содержит агрегированную статистику по источникам записей.

.Описание столбцов представления `PLG$PROF_RECORD_SOURCE_STATS_VIEW`
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Наименование столбца
^| Тип данных
^| Описание

|PROFILE_ID
|BIGINT
|идентификатор сессии профилирования

|STATEMENT_ID
|BIGINT
|идентификатор оператора

|STATEMENT_TYPE
|VARCHAR(20)
|типа оператора BLOCK, FUNCTION, PROCEDURE или TRIGGER

|PACKAGE_NAME
|CHAR(63)
|Имя пакета

|ROUTINE_NAME
|CHAR(63)
|Имя функции, процедуры или триггера

|PARENT_STATEMENT_ID
|BIGINT
|идентификатор родительского оператора

|PARENT_STATEMENT_TYPE
|VARCHAR(20)
|типа родительского оператора BLOCK, FUNCTION, PROCEDURE или TRIGGER

|PARENT_ROUTINE_NAME
|CHAR(63)
|Имя родительской функции, процедуры или триггера

|SQL_TEXT
|BLOB SUB_TYPE TEXT
|SQL текст для типа BLOCK

|CURSOR_ID
|BIGINT
|идентификатор курсора

|NAME
|CHAR(63)
|имя явно объявленного курсора

|CURSOR_LINE_NUM
|INTEGER
|номер строки в которой определён курсор

|CURSOR_COLUMN_NUM
|INTEGER
|номер столбца в котором определён курсор

|RECORD_SOURCE_ID
|BIGINT
|идентификатор источника записей

|PARENT_RECORD_SOURCE_ID
|BIGINT
|идентификатор родительского источника записей

|LEVEL
|INTEGER
|уровень метода доступа. Необходим для расчёта отступов при конструировании плана.

|ACCESS_PATH
|VARCHAR(255)
|путь доступа к источнику записи

|OPEN_COUNTER
|BIGINT
|количество открытий источника записи

|OPEN_MIN_ELAPSED_TIME
|BIGINT
|Минимальное время открытия источника записи (в наносекундах)

|OPEN_MAX_ELAPSED_TIME
|BIGINT
|Максимальное время открытия источника записи (в наносекундах)

|OPEN_TOTAL_ELAPSED_TIME
|BIGINT
|Накопленное время открытия источника записи (в наносекундах)

|OPEN_AVG_ELAPSED_TIME
|BIGINT
|Среднее время открытия источника записи (в наносекундах)

|FETCH_COUNTER
|BIGINT
|Количество извлечений из источника записи

|FETCH_MIN_ELAPSED_TIME
|BIGINT
|Минимальное время извлечения записи из источника записи (в наносекундах)

|FETCH_MAX_ELAPSED_TIME
|BIGINT
|Максимальное время извлечения записи из источника записи (в наносекундах)

|FETCH_TOTAL_ELAPSED_TIME
|BIGINT
|Накопленное время извлечения записей из источника записи (в наносекундах)

|FETCH_AVG_ELAPSED_TIME
|BIGINT
|Среднее время извлечения записей из источника записи (в наносекундах)
|===

[source,sql]
----
select rstat.profile_id,
       rstat.statement_id,
       sta.statement_type,
       sta.package_name,
       sta.routine_name,
       sta.parent_statement_id,
       sta_parent.statement_type parent_statement_type,
       sta_parent.routine_name parent_routine_name,
       (select sql_text
          from plg$prof_statements
          where profile_id = rstat.profile_id and
                statement_id = coalesce(sta.parent_statement_id, rstat.statement_id)
       ) sql_text,
       rstat.cursor_id,
       cur.name cursor_name,
       cur.line_num cursor_line_num,
       cur.column_num cursor_column_num,
       rstat.record_source_id,
       recsrc.parent_record_source_id,
       recsrc.level,
       recsrc.access_path,
       cast(sum(rstat.open_counter) as bigint) open_counter,
       min(rstat.open_min_elapsed_time) open_min_elapsed_time,
       max(rstat.open_max_elapsed_time) open_max_elapsed_time,
       cast(sum(rstat.open_total_elapsed_time) as bigint) open_total_elapsed_time,
       cast(sum(rstat.open_total_elapsed_time) / nullif(sum(rstat.open_counter), 0) as bigint) open_avg_elapsed_time,
       cast(sum(rstat.fetch_counter) as bigint) fetch_counter,
       min(rstat.fetch_min_elapsed_time) fetch_min_elapsed_time,
       max(rstat.fetch_max_elapsed_time) fetch_max_elapsed_time,
       cast(sum(rstat.fetch_total_elapsed_time) as bigint) fetch_total_elapsed_time,
       cast(sum(rstat.fetch_total_elapsed_time) / nullif(sum(rstat.fetch_counter), 0) as bigint) fetch_avg_elapsed_time,
       cast(coalesce(sum(rstat.open_total_elapsed_time), 0) + coalesce(sum(rstat.fetch_total_elapsed_time), 0) as bigint) open_fetch_total_elapsed_time
  from plg$prof_record_source_stats rstat
  join plg$prof_cursors cur
    on cur.profile_id = rstat.profile_id and
       cur.statement_id = rstat.statement_id and
       cur.cursor_id = rstat.cursor_id
  join plg$prof_record_sources recsrc
    on recsrc.profile_id = rstat.profile_id and
       recsrc.statement_id = rstat.statement_id and
       recsrc.cursor_id = rstat.cursor_id and
       recsrc.record_source_id = rstat.record_source_id
  join plg$prof_statements sta
    on sta.profile_id = rstat.profile_id and
       sta.statement_id = rstat.statement_id
  left join plg$prof_statements sta_parent
    on sta_parent.profile_id = sta.profile_id and
       sta_parent.statement_id = sta.parent_statement_id
  group by rstat.profile_id,
           rstat.statement_id,
           sta.statement_type,
           sta.package_name,
           sta.routine_name,
           sta.parent_statement_id,
           sta_parent.statement_type,
           sta_parent.routine_name,
           rstat.cursor_id,
           cur.name,
           cur.line_num,
           cur.column_num,
           rstat.record_source_id,
           recsrc.parent_record_source_id,
           recsrc.level,
           recsrc.access_path
  order by coalesce(sum(rstat.open_total_elapsed_time), 0) + coalesce(sum(rstat.fetch_total_elapsed_time), 0) desc
----
